project:
  type: website
  output-dir: docs

website:
  title: "FINAL PROJECT"
  
  
  navbar:
    website:
    
  sidebar:
    style: "floating"
    type: dark
    border: True
    search: true
    contents:
      
      - section: "Final_Project"
        contents:
          - Dummy1.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd
      
    
      

      

    
settings:
  responsive: true


editor: visual

