project:
  type: website
  output-dir: docs

website:
  title: "Comparative Study of Top Football Leagues Using FIFA 22 Data"
  
  navbar:
    website:
    
  sidebar:
    style: "floating"
    type: dark
    border: True
    search: true
    contents:
      
      - section: "Final_Project"
        contents:
          - INTRODUCTION.qmd
          - DATA SET.qmd
          - layout-jupyter.qmd
      
    
      

      

    
settings:
  responsive: true


editor: visual

