project:
  type: website
  title: "My Learning Site"
  navigation:
    - text: "Home"
      href: FINALPROJECT.qmd
    

website:
  title: "FIFA_22"
  navbar:
    left:
    - FINALPROJECT.qmd
    
    

format:
  html:
    theme: sandstone